FROM ubuntu:latest

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 blop 

USER root

# Replace shell with bash so we can source files
# RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Install base dependencies
RUN apt-get update && apt-get install -y -q --no-install-recommends \
        apt-transport-https \
        build-essential \
        ca-certificates \
        python3 \
        sudo \
        curl \
        git \
        openssl \
        libssl-dev \
        openssh-server \
        net-tools 

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 15.9.0

WORKDIR $NVM_DIR

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN npm install npm@latest -g

RUN  echo 'blop:blop' | chpasswd

RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]