---
- hosts: servers
  become: yes

  vars:
    - appdir: /var/www/html

  tasks:

  - name: Nettoyage des anciens serveur nodejs
    shell: cd '{{appdir}}' && npm run pm2del
    ignore_errors: yes

  - name: Lancement du server nodejs
    shell: cd '{{appdir}}' && npm run pm2r
    ignore_errors: yes

  - name: Recuperation des adresses ip
    debug:
      msg: "{{ hostvars[inventory_hostname]['ansible_%s' | format(item)].ipv4.address }}"
    with_items: "{{ ansible_interfaces | difference(['lo',ansible_interfaces])}}"
