---
- hosts: servers
  become: yes

  vars:
    
    - gitrepo: https://9cbef11163ae1108cbc9d2a3dd11a553a5954695@github.com/morgan-grt/ansible_project_nodejs.git
    - appdir: /var/www/html
    - appuser: www-data

  tasks:

  - name: Creation des repertoires
    file:
      state: directory
      path: '{{appdir}}'
      owner: '{{appuser}}'
      group: '{{appuser}}'
      mode: 0755

  - name: Clonage du depot git
    git:
      repo: '{{gitrepo}}'
      dest: '{{appdir}}'
      force: yes

  - name: Installation des packages npm
    npm:
      path: '{{appdir}}'

  - name: Installation des certificats ssl
    shell: cd '{{appdir}}' && mkdir -p certs/ && openssl req -x509 -newkey rsa:4096 -keyout certs/key.pem -out certs/cert.pem -days 365 -passout pass':'blop -batch

  - name: Lancement du server
    shell: cd '{{appdir}}' && npm run pm2r
    ignore_errors: yes

  - name: Recuperation des adresses ip
    debug:
      msg: "{{ hostvars[inventory_hostname]['ansible_%s' | format(item)].ipv4.address }}"
    with_items: "{{ ansible_interfaces | difference(['lo',ansible_interfaces])}}"
