---
- hosts: servers
  become: yes

  vars:
    
    - gitrepo: https://github.com/morgan-grt/ansible_project_nodejs.git
    - appdir: /var/www/html
    - appuser: www-data

  tasks:

  - name: Creation des repertoires
    file:
      state: directory
      path: '{{appdir}}'
      owner: '{{appuser}}'
      group: '{{appuser}}'
      mode: 0755

  - name: Clonage du depot git
    git:
      repo: '{{gitrepo}}'
      dest: '{{appdir}}'
      force: yes

  - name: Installation des packages npm
    npm:
      path: '{{appdir}}'

  - name: Suppression des anciens serveur nodejs
    shell: cd '{{appdir}}' && npm run pm2del
    ignore_errors: yes

  - name: Lancement du server nodejs
    shell: cd '{{appdir}}' && npm run pm2r
    ignore_errors: yes

  - name: Recuperation des adresses ip
    debug:
      msg: "{{ hostvars[inventory_hostname]['ansible_%s' | format(item)].ipv4.address }}"
    with_items: "{{ ansible_interfaces | difference(['lo',ansible_interfaces])}}"
